//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace SelBuk.Core.com.selbuk.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService_GetSales.cfcSoapBinding", Namespace="http://sbqb.webservice.salescontrol.files.store")]
    public partial class WebService_GetSalesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback authenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPaymentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSalesByDateRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReturnsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateInventoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCancelledOrdersByDateRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPurchasesByDateRangeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService_GetSalesService() {
            this.Url = global::SelBuk.Core.Properties.Settings.Default.SelBuk_Core_com_selbuk_www_WebService_GetSalesService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event authenticateCompletedEventHandler authenticateCompleted;
        
        /// <remarks/>
        public event GetPaymentsCompletedEventHandler GetPaymentsCompleted;
        
        /// <remarks/>
        public event GetSalesByDateRangeCompletedEventHandler GetSalesByDateRangeCompleted;
        
        /// <remarks/>
        public event GetReturnsCompletedEventHandler GetReturnsCompleted;
        
        /// <remarks/>
        public event UpdateInventoryCompletedEventHandler UpdateInventoryCompleted;
        
        /// <remarks/>
        public event GetSalesCompletedEventHandler GetSalesCompleted;
        
        /// <remarks/>
        public event GetCancelledOrdersByDateRangeCompletedEventHandler GetCancelledOrdersByDateRangeCompleted;
        
        /// <remarks/>
        public event GetPurchasesByDateRangeCompletedEventHandler GetPurchasesByDateRangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sbqb.webservice.salescontrol.files.store", ResponseNamespace="http://sbqb.webservice.salescontrol.files.store")]
        [return: System.Xml.Serialization.SoapElementAttribute("authenticateReturn")]
        public string authenticate(string strUserName, string strPassword) {
            object[] results = this.Invoke("authenticate", new object[] {
                        strUserName,
                        strPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void authenticateAsync(string strUserName, string strPassword) {
            this.authenticateAsync(strUserName, strPassword, null);
        }
        
        /// <remarks/>
        public void authenticateAsync(string strUserName, string strPassword, object userState) {
            if ((this.authenticateOperationCompleted == null)) {
                this.authenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthenticateOperationCompleted);
            }
            this.InvokeAsync("authenticate", new object[] {
                        strUserName,
                        strPassword}, this.authenticateOperationCompleted, userState);
        }
        
        private void OnauthenticateOperationCompleted(object arg) {
            if ((this.authenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authenticateCompleted(this, new authenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sbqb.webservice.salescontrol.files.store", ResponseNamespace="http://sbqb.webservice.salescontrol.files.store")]
        [return: System.Xml.Serialization.SoapElementAttribute("GetPaymentsReturn")]
        public string GetPayments(string startdate, string enddate, string mytoken, string status, double page) {
            object[] results = this.Invoke("GetPayments", new object[] {
                        startdate,
                        enddate,
                        mytoken,
                        status,
                        page});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPaymentsAsync(string startdate, string enddate, string mytoken, string status, double page) {
            this.GetPaymentsAsync(startdate, enddate, mytoken, status, page, null);
        }
        
        /// <remarks/>
        public void GetPaymentsAsync(string startdate, string enddate, string mytoken, string status, double page, object userState) {
            if ((this.GetPaymentsOperationCompleted == null)) {
                this.GetPaymentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPaymentsOperationCompleted);
            }
            this.InvokeAsync("GetPayments", new object[] {
                        startdate,
                        enddate,
                        mytoken,
                        status,
                        page}, this.GetPaymentsOperationCompleted, userState);
        }
        
        private void OnGetPaymentsOperationCompleted(object arg) {
            if ((this.GetPaymentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPaymentsCompleted(this, new GetPaymentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sbqb.webservice.salescontrol.files.store", ResponseNamespace="http://sbqb.webservice.salescontrol.files.store")]
        [return: System.Xml.Serialization.SoapElementAttribute("GetSalesByDateRangeReturn")]
        public string GetSalesByDateRange(string startdate, string enddate, string mytoken, string status, double page) {
            object[] results = this.Invoke("GetSalesByDateRange", new object[] {
                        startdate,
                        enddate,
                        mytoken,
                        status,
                        page});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSalesByDateRangeAsync(string startdate, string enddate, string mytoken, string status, double page) {
            this.GetSalesByDateRangeAsync(startdate, enddate, mytoken, status, page, null);
        }
        
        /// <remarks/>
        public void GetSalesByDateRangeAsync(string startdate, string enddate, string mytoken, string status, double page, object userState) {
            if ((this.GetSalesByDateRangeOperationCompleted == null)) {
                this.GetSalesByDateRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalesByDateRangeOperationCompleted);
            }
            this.InvokeAsync("GetSalesByDateRange", new object[] {
                        startdate,
                        enddate,
                        mytoken,
                        status,
                        page}, this.GetSalesByDateRangeOperationCompleted, userState);
        }
        
        private void OnGetSalesByDateRangeOperationCompleted(object arg) {
            if ((this.GetSalesByDateRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalesByDateRangeCompleted(this, new GetSalesByDateRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sbqb.webservice.salescontrol.files.store", ResponseNamespace="http://sbqb.webservice.salescontrol.files.store")]
        [return: System.Xml.Serialization.SoapElementAttribute("GetReturnsReturn")]
        public string GetReturns(string startdate, string enddate, string mytoken, string status, double page) {
            object[] results = this.Invoke("GetReturns", new object[] {
                        startdate,
                        enddate,
                        mytoken,
                        status,
                        page});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetReturnsAsync(string startdate, string enddate, string mytoken, string status, double page) {
            this.GetReturnsAsync(startdate, enddate, mytoken, status, page, null);
        }
        
        /// <remarks/>
        public void GetReturnsAsync(string startdate, string enddate, string mytoken, string status, double page, object userState) {
            if ((this.GetReturnsOperationCompleted == null)) {
                this.GetReturnsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReturnsOperationCompleted);
            }
            this.InvokeAsync("GetReturns", new object[] {
                        startdate,
                        enddate,
                        mytoken,
                        status,
                        page}, this.GetReturnsOperationCompleted, userState);
        }
        
        private void OnGetReturnsOperationCompleted(object arg) {
            if ((this.GetReturnsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReturnsCompleted(this, new GetReturnsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sbqb.webservice.salescontrol.files.store", ResponseNamespace="http://sbqb.webservice.salescontrol.files.store")]
        [return: System.Xml.Serialization.SoapElementAttribute("UpdateInventoryReturn")]
        public string UpdateInventory(string mytoken, string sku, double quantity) {
            object[] results = this.Invoke("UpdateInventory", new object[] {
                        mytoken,
                        sku,
                        quantity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateInventoryAsync(string mytoken, string sku, double quantity) {
            this.UpdateInventoryAsync(mytoken, sku, quantity, null);
        }
        
        /// <remarks/>
        public void UpdateInventoryAsync(string mytoken, string sku, double quantity, object userState) {
            if ((this.UpdateInventoryOperationCompleted == null)) {
                this.UpdateInventoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateInventoryOperationCompleted);
            }
            this.InvokeAsync("UpdateInventory", new object[] {
                        mytoken,
                        sku,
                        quantity}, this.UpdateInventoryOperationCompleted, userState);
        }
        
        private void OnUpdateInventoryOperationCompleted(object arg) {
            if ((this.UpdateInventoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateInventoryCompleted(this, new UpdateInventoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sbqb.webservice.salescontrol.files.store", ResponseNamespace="http://sbqb.webservice.salescontrol.files.store")]
        [return: System.Xml.Serialization.SoapElementAttribute("GetSalesReturn")]
        public string GetSales(string mytoken, string order) {
            object[] results = this.Invoke("GetSales", new object[] {
                        mytoken,
                        order});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSalesAsync(string mytoken, string order) {
            this.GetSalesAsync(mytoken, order, null);
        }
        
        /// <remarks/>
        public void GetSalesAsync(string mytoken, string order, object userState) {
            if ((this.GetSalesOperationCompleted == null)) {
                this.GetSalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalesOperationCompleted);
            }
            this.InvokeAsync("GetSales", new object[] {
                        mytoken,
                        order}, this.GetSalesOperationCompleted, userState);
        }
        
        private void OnGetSalesOperationCompleted(object arg) {
            if ((this.GetSalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalesCompleted(this, new GetSalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sbqb.webservice.salescontrol.files.store", ResponseNamespace="http://sbqb.webservice.salescontrol.files.store")]
        [return: System.Xml.Serialization.SoapElementAttribute("GetCancelledOrdersByDateRangeReturn")]
        public string GetCancelledOrdersByDateRange(string startdate, string enddate, string mytoken, double page) {
            object[] results = this.Invoke("GetCancelledOrdersByDateRange", new object[] {
                        startdate,
                        enddate,
                        mytoken,
                        page});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCancelledOrdersByDateRangeAsync(string startdate, string enddate, string mytoken, double page) {
            this.GetCancelledOrdersByDateRangeAsync(startdate, enddate, mytoken, page, null);
        }
        
        /// <remarks/>
        public void GetCancelledOrdersByDateRangeAsync(string startdate, string enddate, string mytoken, double page, object userState) {
            if ((this.GetCancelledOrdersByDateRangeOperationCompleted == null)) {
                this.GetCancelledOrdersByDateRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCancelledOrdersByDateRangeOperationCompleted);
            }
            this.InvokeAsync("GetCancelledOrdersByDateRange", new object[] {
                        startdate,
                        enddate,
                        mytoken,
                        page}, this.GetCancelledOrdersByDateRangeOperationCompleted, userState);
        }
        
        private void OnGetCancelledOrdersByDateRangeOperationCompleted(object arg) {
            if ((this.GetCancelledOrdersByDateRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCancelledOrdersByDateRangeCompleted(this, new GetCancelledOrdersByDateRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://sbqb.webservice.salescontrol.files.store", ResponseNamespace="http://sbqb.webservice.salescontrol.files.store")]
        [return: System.Xml.Serialization.SoapElementAttribute("GetPurchasesByDateRangeReturn")]
        public string GetPurchasesByDateRange(string startdate, string enddate, string mytoken, string status, double page) {
            object[] results = this.Invoke("GetPurchasesByDateRange", new object[] {
                        startdate,
                        enddate,
                        mytoken,
                        status,
                        page});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPurchasesByDateRangeAsync(string startdate, string enddate, string mytoken, string status, double page) {
            this.GetPurchasesByDateRangeAsync(startdate, enddate, mytoken, status, page, null);
        }
        
        /// <remarks/>
        public void GetPurchasesByDateRangeAsync(string startdate, string enddate, string mytoken, string status, double page, object userState) {
            if ((this.GetPurchasesByDateRangeOperationCompleted == null)) {
                this.GetPurchasesByDateRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPurchasesByDateRangeOperationCompleted);
            }
            this.InvokeAsync("GetPurchasesByDateRange", new object[] {
                        startdate,
                        enddate,
                        mytoken,
                        status,
                        page}, this.GetPurchasesByDateRangeOperationCompleted, userState);
        }
        
        private void OnGetPurchasesByDateRangeOperationCompleted(object arg) {
            if ((this.GetPurchasesByDateRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPurchasesByDateRangeCompleted(this, new GetPurchasesByDateRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void authenticateCompletedEventHandler(object sender, authenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPaymentsCompletedEventHandler(object sender, GetPaymentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPaymentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPaymentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSalesByDateRangeCompletedEventHandler(object sender, GetSalesByDateRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalesByDateRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalesByDateRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetReturnsCompletedEventHandler(object sender, GetReturnsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReturnsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReturnsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateInventoryCompletedEventHandler(object sender, UpdateInventoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateInventoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateInventoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetSalesCompletedEventHandler(object sender, GetSalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCancelledOrdersByDateRangeCompletedEventHandler(object sender, GetCancelledOrdersByDateRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCancelledOrdersByDateRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCancelledOrdersByDateRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPurchasesByDateRangeCompletedEventHandler(object sender, GetPurchasesByDateRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPurchasesByDateRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPurchasesByDateRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591