//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 

namespace SelBuk.Core.Models
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PurchaseAdd
    {

        private Purchases[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Purchases", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Purchases[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class Purchases
    {

        private decimal discountField;

        private decimal subTotalField;

        private bool isReceivedField;

        private bool isPaidField;

        private decimal amountPendingField;

        private decimal shippingField;

        private decimal taxField;

        private decimal totalField;

        private string salesCodeField;

        private string txnIDField;

        private string wareHouseCodeField;

        private string orderSBIDField;

        private string shipDateField;

        private string commentsField;

        private string timeCreatedField;

        private string moreRecordsField;

        private PurchaseItemSales[] itemSalesField;

        private Vendor vendorField;

        public Vendor Vendor
        {
            get
            {
                return this.vendorField;
            }
            set 
            {
                this.vendorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal SubTotal
        {
            get
            {
                return this.subTotalField;
            }
            set
            {
                this.subTotalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsReceived
        {
            get
            {
                return this.isReceivedField;
            }
            set
            {
                this.isReceivedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsPaid
        {
            get
            {
                return this.isPaidField;
            }
            set
            {
                this.isPaidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal AmountPending
        {
            get
            {
                return this.amountPendingField;
            }
            set
            {
                this.amountPendingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Shipping
        {
            get
            {
                return this.shippingField;
            }
            set
            {
                this.shippingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalesCode
        {
            get
            {
                return this.salesCodeField;
            }
            set
            {
                this.salesCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TxnID
        {
            get
            {
                return this.txnIDField;
            }
            set
            {
                this.txnIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WareHouseCode
        {
            get
            {
                return this.wareHouseCodeField;
            }
            set
            {
                this.wareHouseCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderSBID
        {
            get
            {
                return this.orderSBIDField;
            }
            set
            {
                this.orderSBIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipDate
        {
            get
            {
                return this.shipDateField;
            }
            set
            {
                this.shipDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TimeCreated
        {
            get
            {
                return this.timeCreatedField;
            }
            set
            {
                this.timeCreatedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string moreRecords
        {
            get
            {
                return this.moreRecordsField;
            }
            set
            {
                this.moreRecordsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemSales", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PurchaseItemSales[] ItemSales
        {
            get
            {
                return this.itemSalesField;
            }
            set
            {
                this.itemSalesField = value;
            }
        }
    }

    public partial class Vendor
    {
        public string nameField { get; set; }

        public string addr1Field { get; set; }

        public string addr2Field { get; set; }

        public string countryField { get; set; }

        public string cityField { get; set; }

        public string stateField { get; set; }

        public string postalField { get; set; }

        public string emailField { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRoot(ElementName = "ItemSales")]
    public partial class PurchaseItemSales
    {

        private string itemSalesListIDField;

        private string itemSalesSBIDField;

        private string itemSBProductIDField;

        private string itemSalesFullNameField;

        private string itemDescField;

        private decimal itemSalesQtyField;

        private bool itemSalesTaxedField;

        private decimal itemSalesTaxTotalField;

        private decimal itemSalesPriceField;

        private decimal itemPriceUnitField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemSalesListID
        {
            get
            {
                return this.itemSalesListIDField;
            }
            set
            {
                this.itemSalesListIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemSalesSBID
        {
            get
            {
                return this.itemSalesSBIDField;
            }
            set
            {
                this.itemSalesSBIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemSBProductID
        {
            get
            {
                return this.itemSBProductIDField;
            }
            set
            {
                this.itemSBProductIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemSalesFullName
        {
            get
            {
                return this.itemSalesFullNameField;
            }
            set
            {
                this.itemSalesFullNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemDesc
        {
            get
            {
                return this.itemDescField;
            }
            set
            {
                this.itemDescField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ItemSalesQty
        {
            get
            {
                return this.itemSalesQtyField;
            }
            set
            {
                this.itemSalesQtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ItemSalesTaxed
        {
            get
            {
                return this.itemSalesTaxedField;
            }
            set
            {
                this.itemSalesTaxedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ItemSalesTaxTotal
        {
            get
            {
                return this.itemSalesTaxTotalField;
            }
            set
            {
                this.itemSalesTaxTotalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ItemSalesPrice
        {
            get
            {
                return this.itemSalesPriceField;
            }
            set
            {
                this.itemSalesPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ItemPriceUnit
        {
            get
            {
                return this.itemPriceUnitField;
            }
            set
            {
                this.itemPriceUnitField = value;
            }
        }
    }
}